### ISSUE TITLE
Stream Transform - Not Implemented?

### ISSUE THREAD

**Issue by iwasaki-kenta** [chfritz/meteor-ros#2]
Hey,

Was looking if there was any work done for ROS with Meteor and was really interested in your package. I tried to set it up with a custom message and subscribed to an endpoint though and there seems to be an issue with transforming custom ROS messages into Meteor.

```
I20160904-01:26:03.506(8)? [/my_node][INFO] 2016-09-04 01:26:03.503+0800: Connecting to ROS Master at http://localhost:11311
I20160904-01:26:03.559(8)? [INFO] 2016-09-04 01:26:03.559+0800: Connected to master!
W20160904-01:26:03.938(8)? (STDERR) _stream_transform.js:142
W20160904-01:26:03.941(8)? (STDERR)   throw new Error('not implemented');
W20160904-01:26:03.941(8)? (STDERR)   ^
W20160904-01:26:03.941(8)? (STDERR) 
W20160904-01:26:03.941(8)? (STDERR) Error: not implemented
W20160904-01:26:03.941(8)? (STDERR)     at DeserializeStream.Transform._transform (_stream_transform.js:142:9)
W20160904-01:26:03.941(8)? (STDERR)     at DeserializeStream.Transform._read (_stream_transform.js:167:10)
W20160904-01:26:03.941(8)? (STDERR)     at DeserializeStream.Transform._write (_stream_transform.js:155:12)
W20160904-01:26:03.942(8)? (STDERR)     at doWrite (_stream_writable.js:300:12)
W20160904-01:26:03.942(8)? (STDERR)     at writeOrBuffer (_stream_writable.js:286:5)
W20160904-01:26:03.942(8)? (STDERR)     at DeserializeStream.Writable.write (_stream_writable.js:214:11)
W20160904-01:26:03.942(8)? (STDERR)     at Socket.ondata (_stream_readable.js:542:20)
W20160904-01:26:03.942(8)? (STDERR)     at emitOne (events.js:77:13)
W20160904-01:26:03.943(8)? (STDERR)     at Socket.emit (events.js:169:7)
W20160904-01:26:03.943(8)? (STDERR)     at readableAddChunk (_stream_readable.js:153:18)
```

This is the message: `bool[5] state`

Also, here is the code:

```
import { Meteor } from 'meteor/meteor';
import { ROS } from 'meteor/chfritz:ros';

Meteor.startup(() => {
    let ros = ROS({messages: ['custom_msgs/Pneumatics'], services: []});
    ros.subscribe("/pneumatics", "custom_msgs/Pneumatics", 100);
});
```

Any help would be much appreciated.

Thanks,

**Comment by chfritz** [comment]
Hi Dranithix,

Indeed I have run into this problem too and have a fix. This error is coming from an incompatibility of node-4.5 with the current version of rosnodejs. I have a pull request into rosnodejs that fixes this (https://github.com/RethinkRobotics-opensource/rosnodejs/pull/31).

I've just published a new version of this package that uses the branch of the pull-request for now. So if you upgrade to `chfritz:ros@0.1.0` it should work.

Please let me know if you run into any other issues. This package is still bleeding-edge, so feedback is very helpful.

Thanks!

Fixed in 0404d8a0454b0988c79e9dd0acb3c8598a207452.
